version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hello_nestjs
    container_name: hello_nestjs
    ports:
      - "80:4000"
      - "81:4001"
    env_file:
      - .env
    networks:
      - hello_nestjs
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      - hello_nestjs

  redis:
    image: redis:6.0
    container_name: redis
    restart: unless-stopped
    networks:
      - hello_nestjs
networks:
  hello_nestjs:
    driver: bridge
    name: hello_nestjs    